# Generated by Django 5.2.1 on 2025-07-21 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonogramimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonogram_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonogramimage',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_nonograms', to='image.originimage'),
        ),
    ]
