# Generated by Django 5.2.1 on 2025-08-13 07:55

import image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originimage',
            name='image',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
