[uwsgi]
chdir = /home/ubuntu/nonogram/nonogram
module = nonogram.wsgi:application
home = /home/ubuntu/nonogram
master = true
processes = 5
socket = /home/ubuntu/nonogram/nonogram/nonogram.sock
chmod-socket = 660
vacuum = true
daemonize = /home/ubuntu/nonogram/nonogram/uwsgi.log

